# Generated by Django 4.2.1 on 2023-05-24 18:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_created_date_alter_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 18, 45, 12, 71160, tzinfo=datetime.timezone.utc), verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 18, 45, 12, 71160, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Задача')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 5, 24, 18, 45, 12, 71160, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2023, 5, 24, 18, 45, 12, 71160, tzinfo=datetime.timezone.utc), verbose_name='Дата обновления')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Дата закрытия')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Проект')),
            ],
        ),
    ]
