# Generated by Django 4.2.1 on 2023-05-24 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_start_date_project_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 19, 36, 51, 866675, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 19, 36, 51, 866675, tzinfo=datetime.timezone.utc), verbose_name='Дата обновления'),
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
