# Generated by Django 4.2.1 on 2023-05-24 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_alter_project_created_date_alter_project_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Задача')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 5, 24, 19, 36, 51, 867675, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2023, 5, 24, 19, 36, 51, 867675, tzinfo=datetime.timezone.utc), verbose_name='Дата обновления')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Дата закрытия')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
